name: Crear APK de Android

on:
  push:
    branches:
      - main
      - principal
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Compilar APK
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false

      - name: Compilar APK con Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          repository_root: .
          workdir: .
          buildozer_version: stable

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: overlord-debug-apk
          path: ${{ steps.buildozer.outputs.filename }}
          if-no-files-found: error
